### ISSUE TITLE
requests hanging

### ISSUE THREAD

**Issue by sampaccoud** [Mangopay/mangopay2-python-sdk#100]
After a high number of successive requests (that are tamed to respect the rate limits given by Mangopay here https://docs.mangopay.com/guide/rate-limiting), my requests randomly hang and never return nor timeout.

**Comment by mickaelpois** [comment]
Hello @sampaccoud, 

Could you give us some extra-info about your requests? (endpoints, date and time of these requests, etc.)

I hope we will help you very soon with that !

**Comment by sampaccoud** [comment]
I have solved this on my side. It was caused by the server being short in memory.
