### ISSUE TITLE
Money tranformation

### ISSUE THREAD

**Issue by ddemid** [Mangopay/mangopay2-python-sdk#103]
Hello,

If there is a special class for `Money` objects and it has `Decimal` amount inside, why don't you do the following transformation automatically?

> An amount of money in the smallest sub-division of the currency, e.g. 12.60 EUR would be represented as 1260 whereas 12 JPY would be represented as just 12)

Even this SDK example says:

>`debited_funds=Money(amount=10, currency='EUR'),  # Create a EUR 10.00 transfer`

But this is not true, this will create a 0.10 EUR Transaction.

Thanks.

**Comment by mickaelpois** [comment]
Hi @ddemid,

Thanks for your feedback.

Firstly, you are totally right, our SDK example has a bad comment, it should be "#Create a EUR 0.10 transfer" as smaller subdivision of EUR is cents.
Then, what would you except from Money class exactly ?

Mickaël

**Comment by ddemid** [comment]
Hi Mickaël,

I would rather have this transformation (/100) hidden in the black box of the SDK from the end user. 
If SDK accepts Money object, why would anyone think of /100? It's pretty logical to have the transfomation inside SDK methods.

**Comment by mickaelpois** [comment]
Hello @ddemid,

Thanks for your feedback.
We will take your remark into account, and let you know here every update concerning this proposal.

Mickaël

**Comment by mangomaxoasis** [comment]
Hi @ddemid 
Our syntax at the moment is not to do the transformation, as this is common practice in our community 
Best,
Max
