### ISSUE TITLE
Can't set CreditedUserId when making a DirectPayin

### ISSUE THREAD

**Issue by TamasNo1** [Mangopay/mangopay2-python-sdk#105]
When trying to make a DirectPayin and set `credited_user_id`, the field is ignored when making the API call.

Example:
```
payin = DirectPayIn(
    author_id=customer_user_id,
    credited_user_id=settings.TECHNICAL_USER_ID,
    credited_wallet_id=customer_wallet_id,
    debited_funds=Money(amount=full_amount, currency='GBP'),
    fees=Money(amount=fees, currency='GBP'),
    card_id=card_id,
)
res = payin.save()
assert 'credited_user_id' in res
```

**Comment by mickaelpois** [comment]
Hello @TamasNo1,

Thanks a lot for you feedback !
It seems to be something wrong yes, we will take a look at this issue immediatly.
I'll give you further information about its resolution.

Mickaël

**Comment by TamasNo1** [comment]
Hi @mickaelpois, do you have any update on this issue?

**Comment by mickaelpois** [comment]
Hello @TamasNo1, no update yet, but we are working on it !

**Comment by NameX44** [comment]
Hi,

You have to set full user object, full wallet object and full card object : 

```
payload = {
            'credited_user': credited_user,
            'credited_wallet': credited_user.wallets[0],
            'author': debited_user,
            'debited_funds': debited_funds,
            'fees': fees,
            'card': debited_user.cards.get(self.mangopay_card_id)
        }
```
So, you have to request for users and their wallets and card to create this request. It's a shame because we are rate limited in number of request but we can't use stored IDs.

**Comment by VivienCormierRM** [comment]
Yep, I'm agree it's a shame, instead of doing only on request you have to do 5 requests.

@mickaelpois Can we do something to reduce the number of request ?

**Comment by Changaco** [comment]
You probably don't have to fetch the full objects, creating and using empty ones like `Wallet(id=…)` or `Card(id=…)` should work. Alternatively using the API names may also work, e.g. `CreditedUserId=…` instead of `credited_user_id=…`.

**Comment by NameX44** [comment]
> You probably don't have to fetch the full objects, creating and using empty ones like Wallet(id=…) or Card(id=…) should work. Alternatively using the API names may also work, e.g. CreditedUserId=… instead of credited_user_id=….

Ah thanks ! It works for this API with empty objects :
```
payload = {
            'credited_user': User(id=self.credited_id),
            'credited_wallet': Wallet(id=self.mangopay_credited_wallet_id),
            'author': User(id=self.debited_id),
            'debited_funds': debited_funds,
            'fees': fees,
            'card': Card(id=self.mangopay_card_id),
        }
```

Documentation should refer to this method.

Btw some APIs can't work like this : see #78 

Thanks @Changaco

**Comment by mickaelpois** [comment]
Hello !

Thanks for your living contribution to this PR !
There is probably a fix to do concerning credited_user_id that is not well taken in account if passed as a parameter, and we will do it ASAP.

And thanks @Changaco for your help on showing how to use stored IDs !

**Comment by gabriellupu** [comment]
We submitted a PR that will address this issue. After the release, you can create PayIns and other similar entities by either:

```python
# Using objects
payin = DirectPayIn(
    author=natural_user,
    credited_user=natural_user,
    credited_wallet=natural_user_wallet,
    debited_funds=Money(amount=100, currency='GBP'),
    fees=Money(amount=100, currency='GBP'),
    card=Card(id='25003527'),
    secure_mode_return_url= "http://www.site.com/",
)

# Using identifier string values
payin = DirectPayIn(
    author_id="25003524",
    credited_user_id="25003525",
    credited_wallet_id="25003526",
    debited_funds=Money(amount=100, currency='GBP'),
    fees=Money(amount=100, currency='GBP'),
    card_id="25003527",
    secure_mode_return_url= "http://www.site.com/",
)
```

Thanks for your contributions for solving this!

**Comment by mickaelpois** [comment]
Thansk @gabriellupu for this !
@TamasNo1, we will release a new version very soon in order to provide you this fix !
