### ISSUE TITLE
Critical serialization error - Inherited objects do not contain all attributes in list

### ISSUE THREAD

**Issue by gabriellupu** [Mangopay/mangopay2-python-sdk#111]
```python
class User(BaseModel):
    email = EmailField(api_name='Email', required=True)
...

class NaturalUser(User):
    first_name = CharField(api_name='FirstName', required=True)
...
```

```python
allUsers = Users.all() 
# returns [
#  {
#    "PersonType": "NATURAL", 
#    "FirstName": "MyName",
#    ...
#  }]

assertIsInstance(users[0], NaturalUser) # OK
self.assertIsNotNone(users[0].first_name) # FAIL
```
Extended objects should be serialized correctly and contain all the attributes, as received from the server.

In order to reveal the issue, I added a test 6aabacdfcf7d5b3063c498706d033b9656baa67d that [fails on travis](https://travis-ci.org/Mangopay/mangopay2-python-sdk/jobs/230610405)

**Comment by mickaelpois** [comment]
@gabriellupu I guess this issue can be closed, right ?

**Comment by gabriellupu** [comment]
actually I think it's not. I can add a test for it on a branch
