### ISSUE TITLE
Documentation update on NaturalUser.get

### ISSUE THREAD

**Issue by Maldus512** [Mangopay/mangopay2-python-sdk#116]
The usage page states you can retrieve an existing user by calling `NaturalUser.get(i)`. The example implies that i is the index in the list of users, but it seems to work with the user id.

I base this convinction on the following test script:
`users = User.all()`
`for i in range(len(users)):`
`    try:`
`        print NaturalUser.get(i)`
`    except NaturalUser.DoesNotExist:`
`        print 'The natural user {} does not exist'.format(i)`
`for u in users:`
`    print NaturalUser.get(u.id)`

which for me outputs
`The natural user 0 does not exist`
`The natural user 1 does not exist`
`The natural user 2 does not exist`
`victor@hugo.com`
`victor@hugo.com`
`victor@hugo.com`

**Comment by mickaelpois** [comment]
Hello @Maldus512,

I've added a extra info on this code snippet on this usage page to be more precise.
Thanks for your feedback !

Mickaël
