### ISSUE TITLE
Update a LegalUser with no LegalRepresentativeAddress

### ISSUE THREAD

**Issue by b0uh** [Mangopay/mangopay2-python-sdk#126]
For a legal user `LegalRepresentativeAddress` is optional, so you can create one without it. But when retrieving such an user, `LegalRepresentativeAddress` is not `None`, it got something like `{"Region": null, "Country": null, "AddressLine2": null, "AddressLine1": null, "PostalCode": null, "City": null}`. That's OK, but the thing is when you try to save your user (for example after you update some fields, it will send a request where `LegalRepresentativeAddress` is not `null` but either with actual data, just a dictionary with empty values so the API return an error.

## How to reproduce the issue

    from mangopay.resources import User, LegalUser

    my_user = LegalUser(
        name='My Company',
        email='email@gmail.com',
        person_type='LEGAL',
        legal_person_type='BUSINESS',
        headquarters_address=Address(
            address_line_1='10 rue des champs',
            city='Nantes',
            postal_code='44000',
            country='FR',
        legal_representative_first_name='John',
        legal_representative_last_name='Doe',
        legal_representative_birthday=606441600,
        legal_representative_nationality='FR',
        legal_representative_country_of_residence='FR',
    )
    my_user.save()
    
    pk = my_user.get_pk()

    my_user2 = User.get(pk)
    my_user2.save()     # <--- crash here, because API returns an error

## The request sent by the SDK when doing the 2nd save()

**HTTP Method:** PUT
**URL:** https://api.sandbox.mangopay.com/v2.01/<ID_CLIENT>/users/legal/<ID_USER>
**HEADERS:**

* Authorization: bearer <TOKEN>
* User-Agent: MangoPay V2 Python/None
* Content-Type: application/json

**DATA:** `{"LegalRepresentativeCountryOfResidence": "FR", "LegalPersonType": "BUSINESS", "LegalRepresentativeFirstName": "John", "LegalRepresentativeLastName": "Doe", "LegalRepresentativeBirthday": 606441600, "LegalRepresentativeAddress": {"Region": null, "Country": null, "AddressLine2": null, "AddressLine1": null, "PostalCode": null, "City": null}, "HeadquartersAddress": {"Region": null, "Country": "FR", "AddressLine2": null, "AddressLine1": "10 rue des champs", "PostalCode": "44000", "City": "Nantes"}, "Name": "My Company", "LegalRepresentativeNationality": "FR", "Email": "bb@bb.bb", "KYCLevel": "LIGHT", "PersonType": "LEGAL"}`

## API response

`{"Message":"One or several required parameters are missing or incorrect. An incorrect resource ID also raises this kind of error.","Type":"param_error","Id":"2790e064-da7d-44e7-b71d-8af61d04bdbb#1504702107","Date":1504702108.0,"errors":{"LegalRepresentativeAddress.AddressLine1":"The AddressLine1 field is required.","LegalRepresentativeAddress.City":"The City field is required.","LegalRepresentativeAddress.Country":"The Country field is required."}}`

## Workaround
Set `LegalRepresentativeAddress` to `None` if its dictionary is actually empty values.

    my_user2 = User.get(pk)
    my_user2.LegalRepresentativeAddress = None
    my_user2.save()

**Comment by mickaelpois** [comment]
Hello @b0uh !

Thanks for your feedback.
I can easily understand it could be painful to process the way you have perfectly described above.
We could try to add an extra check for this kind of case, but we want to let our SDK the more simple as possible, and let every functional complexity to our API.
Because we don't provide any PATCH method (yet), it's difficult to easily handle this case, so your workaround seems to be the best solution today.
