### ISSUE TITLE
Retrieving Card Registration on stateless backend

### ISSUE THREAD

**Issue by AvBrocklehurst** [Mangopay/mangopay2-python-sdk#127]
When creating a card registration you have to first create an instance on the server using the SDK, send the information down to the browser to use the card registration JS library and then back to the server to complete the registration. This is fine if you can keep the card registration object in memory, but if you're using a stateless backend it doesn't appear to be a way to retrieve the card registration object back with the SDK. 

Could I propose a solution that allows a user to store the id of the card registration in a database and then recall its ID and use it to recall a previous card registration like so?

```
recalled_card_registration = CardRegistration(id=recalled_id)
```

**Comment by hobailey** [comment]
I've possibly misunderstood, but when you pass the info "back to the server to complete the registration", why can't you pass the `CardRegistrationId` as well?

**Comment by AvBrocklehurst** [comment]
You can pass the CardRegistrationID. But using the SDK there is no apparent way to recall the previous CardRegistration object with it to complete the registration.

**Comment by hobailey** [comment]
Ah ok, I see what you mean - well this does exist in the API, and should of course be in the SDK here. We'll get that added asap :-)

**Comment by Changaco** [comment]
@AvBrocklehurst

```python
recalled_card_registration = CardRegistration.get(recalled_id)
```

**Comment by hobailey** [comment]
Well that's what I was thinking, but I assumed that this didn't respond to @AvBrocklehurst's case somehow?

**Comment by Changaco** [comment]
To complete my previous answer: the JS code sends the card registration data straight from the payer's browser to mangopay's API, so in fact there's no need to fetch the `CardRegistration` server-side.

**Comment by AvBrocklehurst** [comment]
From the documentation:

"Update the card_registration instance with the response provided by the Mangopay Tokenization server.

card_registration.registration_data = response
card_registration.save()
"

If this step is needed, then there's need to fetch the card registration server side. 

@Changaco 
```recalled_card_registration = CardRegistration.get(recalled_id)``` I hadn't seen this in the documentation at all?

**Comment by Changaco** [comment]
> If this step is needed, then there's need to fetch the card registration server side.

It's not needed, but even if it was you could simply do this:

```python
CardRegistration(id=recalled_id, registration_data=response).save()
```

> I hadn't seen this in the documentation at all?

The way to fetch an object by its ID is the same for all classes, they may not be all shown in the documentation.

**Comment by AvBrocklehurst** [comment]
Okay great! So a card registration is completed when it goes through the card registration JS kit, and there is no need to send anything back to the server? The valid card can then simply be retrieved by user.cards.get(card.id)?

**Comment by Changaco** [comment]
Yes, the JS kit completes the registration and returns the card ID, which you can then use to create a payin.

**Comment by AvBrocklehurst** [comment]
Fantastic, so what is the point of the step:

"Update the card_registration instance with the response provided by the Mangopay Tokenization server.

card_registration.registration_data = response
card_registration.save()"

Is it redundant?
