### ISSUE TITLE
How can we remove or deactivate cards

### ISSUE THREAD

**Issue by EmilioK97** [Mangopay/mangopay2-python-sdk#133]
We need to implement the option of deactivate a client's card and the call https://docs.mangopay.com/endpoints/v2.01/cards#e182_deactivate-a-card seems to be the right one. It is implemented in the python sdk or how can we remove a card?

**Comment by mickaelpois** [comment]
Hello @EmilioK97 
It seems this endpoint support is actually missing for Python SDK.
I'll try to make it available ASAP (this week I hope) and release a new minor version for you.

Thanks for pointing it, and thanks a lot for your patience.

Mickaël

**Comment by mickaelpois** [comment]
Hi @EmilioK97,
#138 will add this missing resource and fix your issue, I'll release a minor version shortly !

Have a nice day

Mickaël
