### ISSUE TITLE
No Redis Storage

### ISSUE THREAD

**Issue by SBillion** [Mangopay/mangopay2-python-sdk#135]
It's impossible to keep a webapp stateless with your StaticStorage or FileStorage.
The best way to achieve this would be to have a Redis one

**Comment by mangomaxoasis** [comment]
Hi @SBillion 
For the time being Redis is not on our medium term Road Map
Max

**Comment by SBillion** [comment]
Thank you for your fast answer ;)

**Comment by mangomaxoasis** [comment]
Issue closed
