### ISSUE TITLE
Cannot get an individual transaction for a user.

### ISSUE THREAD

**Issue by benjackwhite** [Mangopay/mangopay2-python-sdk#140]
As part of the 3D Secure process I am trying to use the given `transactionId` from the redirect to fetch the transaction from the SDK to verify the status. With cards it seems you can do:

```
user.cards.get(card_id)
```

...but when I try the same for transactions I get an exception due to the `user_id` not getting set correctly...

```
> user.transactions.get(transaction_id)

ERROR:mangopay:API ERROR: status_code: 400 | url: https://api.sandbox.mangopay.com/v2.01/company/users/%(user_id)s/transactions/33333333 | method: GET | data: None | headers: {'Date': 'Wed, 01 Nov 2017 14:51:03 GMT', 'Connection': 'close', 'Content-Type': 'text/html; charset=us-ascii', 'Content-Length': '324', 'Server': 'Microsoft-HTTPAPI/2.0'} | content: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request - Invalid URL</h2>
<hr><p>HTTP Error 400. The request URL is invalid.</p>
</BODY></HTML>
```

Is this just not supported for the transaction model? If not how are you supposed to get an individual transaction given only a `transaction_id`?

Thanks!

**Comment by paulhristea** [comment]
Hey @benjackwhite!

I believe this is because of a missing relationship declaration on our LegalUser object. We're looking into a solution, will get back to you shortly.

Thank you for bringing this up!

**Comment by paulhristea** [comment]
Hello @benjackwhite, and sorry for the late response.

I've been looking around the SDK and documentation and it doesn't seem like there is an endpoint for getting a Transaction by its id. There are only endpoints for each specific type of Transaction (Get PayIn by id, Get Transfer by id etc). You would therefore have to know what type of Transaction it is that you are retrieving, calling the respective service method (`Transfer.get(id)`).

Does this work for you?

**Comment by mickaelpois** [comment]
Hi @benjackwhite,
Thanks @paulhristea for your answer, it's totally right.
You have to know what kind of transaction you're searching for to get it by its ID (payin, transfer, etc.)
We are not currently providing a generic endpoint which allow you to get any type of transaction thanks to its ID.

It's probably a endpoint we will try to add to our API this year.

Very sorry for this lack, and I hope Paul's proposal could suits you.

Mickaël
