### ISSUE TITLE
No support for rate limits

### ISSUE THREAD

**Issue by Changaco** [Mangopay/mangopay2-python-sdk#144]
This module completely ignores the [API's rate limits](https://docs.mangopay.com/guide/rate-limiting) and provides no easy way to delay background requests when the remaining number of allowed requests is low.

**Comment by mangomaxoasis** [comment]
Hi @Changaco 
We're in the process of implementing this feature on this SDK, as exists on other SKDs.
We'll keep you updated

**Comment by mangomaxoasis** [comment]
Hi @Changaco 
A fix has been merged 
https://github.com/Mangopay/mangopay2-python-sdk/pull/232
Best,
Max
