### ISSUE TITLE
Resource IDs are not checked

### ISSUE THREAD

**Issue by Changaco** [Mangopay/mangopay2-python-sdk#165]
This module does not check that the IDs of resources are integers. That can lead to SQL injection attempts being sent to the Mangopay API.

**Comment by Changaco** [comment]
For example `Document(id='foo', user=User(id='bad'), status='VALIDATION_ASKED').save()` sends a `POST` request to `/users/bad/KYC/documents/foo`.

In fact the variables injected into the URL path are not even escaped: `User.get('bad%xxx')` results in a `GET` request with the invalid path `/users/bad%xxx`, and the server returns a 500 error code instead of a 400.

**Comment by mickaelpois** [comment]
Thanks for pointing this up !
Our resourceIDs are string typed, even if in fact our IDs are integers at the moment.
So we can't add any check for only integer typed resourceIDs, as some of it could become strings (GUID for example) in the future.

We have to analyze the best way to avoid any SQL injections through our SDK in another way.

Mickaël
