### ISSUE TITLE
FileStorageStrategy does not create any token cache file

### ISSUE THREAD

**Issue by zhantz** [Mangopay/mangopay2-python-sdk#166]
Hi,

Running python 3.6 on CentOS 7.4

I want to use the FileStorageStrategy as the handler storage mechanism, setting a specific temporary directory for my app. However, after I made some requests to Users API (successful requests), I couldn't find any cached token file on disk, neither in my temporary directory, nor in /tmp directory (which is the default system tmp directory).

My test script looks like:

```
import mangopay

mangopay.client_id='<CLIENT_ID>'
mangopay.passphrase='<API_KEY>'
mangopay.temp_dir='/tmp/mangotest/'

from mangopay.api import APIRequest
from mangopay.auth import FileStorageStrategy

handler = APIRequest(sandbox=True, timeout=30.0, storage_strategy=FileStorageStrategy())

... (make some Users API requests) ...
```

Have I missed something, is my code incorrect ? Please help me with this.

**Comment by catacraciun** [comment]
@zhantz This will be verified and fixed in #134
