### ISSUE TITLE
Typo LegalUser CompanyName instead of CompanyNumber

### ISSUE THREAD

**Issue by rclement** [Mangopay/mangopay2-python-sdk#170]
Merged PR #167 added the `company_number` field to the `LegalUser` entity, thanks @SBillion for that.
However, I think there is a typo with the API field name in the declaration:

[resources.py:176](https://github.com/Mangopay/mangopay2-python-sdk/blob/6d13a996606ebf27f95816a1b0e188deded7fddd/mangopay/resources.py#L176):
`
company_number = CharField(api_name='CompanyName')`

should be:
`company_number = CharField(api_name='CompanyNumber')`

according to the official API documentation: https://docs.mangopay.com/endpoints/v2.01/users#e258_the-legal-user-object

**Comment by mickaelpois** [comment]
Hello @rclement, thanks for pointing it, I've fixed this typo :)
