### ISSUE TITLE
Error "invalid_client"

### ISSUE THREAD

**Issue by Radiateurs** [Mangopay/mangopay2-python-sdk#171]
Hi,
Whenever I try to send a request using the sdk and using my sandbox credentials, the sdk throw an error {"error":"invalid_client"}

The error is not clear at all. Indeed the client is invalid, but what is invalid ? The password ? The clientID ? Who knows...
I'm stuck on this issue since two days and can't do much to patch this.

**Comment by mickaelpois** [comment]
Hello @Radiateurs,

First of all, your issue: 
It seems your header value was wrong. If you're sure it's right, are you sure you're pointing on api.sanbox.mangopay.com ?

Then, our error message: 
We could cleary enhance this particular case by providing you a clean `error_description` to give you more infos about this issue. But we do not currently want to let anyone know if a clientID exists (by telling as an answer that your password is wrong). We consider that one or many authentication infos (server, clientID, passowrd) are wrong.

At least, what we will do in a short-term vision:
* Add a simple error description pointing all the causes (ie. authentication "triplet" properties that could be wrongly set)
* Add a list of 4xx errors on docs.mangopay.com with many more explainations around causes, and how to resolve it. 

Mickaël

**Comment by Radiateurs** [comment]
I would recommend to modify the documentation of the SDK to specify that the "passphrase" in the authentication is actually the API_KEY. I got tricked by it. Even changing the variable name to something more relevant.

**Comment by mickaelpois** [comment]
@Radiateurs Got it, you're totally right, our naming has changed recently from passphrase to APIKey, and it has not been updated on our SDK docs.
I'll update it very soon.

**Comment by SBillion** [comment]
Hi, 
I try to use mangoopay in Production. The production account has been activated but I still got the error "invalid client". I set the passphrase, the client_id and sandbox=False on instanciation but nothing changes

**Comment by Radiateurs** [comment]
@mickaelpois I also recommend to change the documentation for the V3 authentication

` mangopay.client_id='my client id'
mangopay.passphrase='my password'`

Think about changing the variable name AND the > 'my password'

**Comment by joecridge** [comment]
@SBillion take a look at the discussion on #134. Instantiating `APIRequest` with `sandbox=False` (like the docs suggest) doesn’t actually do anything…

**Comment by mickaelpois** [comment]
#177 will make our code clearer around APIKey use, and use a unified vocabulary (no more passphrase or client password).
