### ISSUE TITLE
APIRequest(sandbox=False) doesn't work

### ISSUE THREAD

**Issue by Radiateurs** [Mangopay/mangopay2-python-sdk#183]
Setting the sandbox argument as False doesn't on a new APIRequest doesn't work.
```
mango_handler = APIRequest(sandbox=False)
```
 You have to do:
```
mangopay.sandbox = False
mango_handler = APIRequest(sandbox=False)
```
Doing this actually works

**Comment by MuraruMihai** [comment]
can't reporduce

**Comment by janfabry** [comment]
This is caused by `if sandbox or mangopay.sandbox:` in `APIRequest.__init__()`. I think the fix is:

`if (sandbox is None and mangopay.sandbox) or sandbox:`

This way, if only if you don't pass the `sandbox` parameter will it take the `mangopay.sandbox` default.

**Comment by mangomaxoasis** [comment]
Hi @Radiateurs 
This issue pointed out by @janfabry will be resolved shortly (similar to issue 134 and 166)
Cheers,
max

**Comment by mangomaxoasis** [comment]
Closed, please contact me if issue persists
