### ISSUE TITLE
Get Ubo by id issue

### ISSUE THREAD

**Issue by guillaume-guerdoux** [Mangopay/mangopay2-python-sdk#198]
Hello,

I'm using the new version of mangopay and trying to implement the ubo declaration process. 
I have an issue with retrieving a UBO by id, and I'm note sure I'm using the best syntax to pass a ubo declaration to 'validation asked' status.
Here is my code for retrieving a UBO : 
 `ubo = Ubo.get(ubo_id, ubo_id= ubo_id, ubo_declaration_id= ubo_declaration_id, user_id= user_id)`
with arguments as the string IDs.
It's returning a Ubo Object but all the fields are None.

For passing a ubo declaration to validation_asked status, I'm using this syntax but I'm not sure it's the best (but it's working): 
`new_ubo_declaration = ubo_declaration.update(ubo_declaration.id, **{"user_id": user_id, "status": "VALIDATION_ASKED"}).execute()`

Could you help me please ?
Thank you very much !

**Comment by samitnuk** [comment]
@guillaume-guerdoux 

Hi!

I'm not an expert, but this is what I use for UBO declaration "validation asking":
```
ubo_declaration.status = UBO_DECLARATION_STATUS_CHOICES.validation_asked
ubo_declaration.save()
```

**Comment by guillaume-guerdoux** [comment]
I found the solution (by looking at the test files) : 
`params = {
                "user_id": user_id,
                "ubo_declaration_id": ubo_declaration_id,
                "ubo_id": ubo_id
            }
        ubo = Ubo.get("", **params)`

**Comment by guillaume-guerdoux** [comment]
> @guillaume-guerdoux
> 
> Hi!
> 
> I'm not an expert, but this is what I use for UBO declaration "validation asking":
> 
> ```
> ubo_declaration.status = UBO_DECLARATION_STATUS_CHOICES.validation_asked
> ubo_declaration.save()
> ```

Hello,
Yes I tried but it's not working :)
