### ISSUE TITLE
NaturalUser only retriever 10 wallets with the object.

### ISSUE THREAD

**Issue by goromachine** [Mangopay/mangopay2-python-sdk#209]
I've found testing my application that when I do a `NaturalUser.get(id)`, this only retrieve 10 wallets inside the object.

Following the [examples on the docs](https://github.com/Mangopay/mangopay2-python-sdk/blob/master/docs/usage.rst#wallet) I do not find anything about this limit of retrieved wallets.

I suppose this is a bug, so here I add some info and Screens to show what I' talking about:
- Total wallets on MangoPay Sandbox Dashboard: 12
- Code that trigger's all the wallets:
<img width="667" alt="Captura de pantalla 2019-12-16 a las 14 27 21" src="https://user-images.githubusercontent.com/12257503/70910623-5e302300-2010-11ea-8914-6578e1c08473.png">
- Debugging result for `NautralUser.wallets`:
<img width="667" alt="Captura de pantalla 2019-12-16 a las 14 27 22" src="https://user-images.githubusercontent.com/12257503/70910646-6ab47b80-2010-11ea-8e09-40ed2f70dcdc.png">

Please, I'm on hurry to solve this problem, so if I could get any feedback on how to solve this I would appreciate it.

Thank you.

**Comment by samitnuk** [comment]
Hi, @goromachine 

Not sure how to solve your issue, but I think the reason for it is that 10 is the default value of items in lists - https://docs.mangopay.com/guide/lists-pagination-management

**Comment by goromachine** [comment]
It could be this, but the thing is that I'm not using pagination at all, so I must receive the whole amount of wallets.

**Comment by samitnuk** [comment]
I think pagination used there by default.

From the above link:
> All the list returned by the API are paginable.
>
> If you miss out any parameter in the query the default value is used.

Since you did not provide pagination params (to be honest, I do not know how you can do this for `user.wallets`) - the default values were used.

**Comment by Riwak** [comment]
Hello @goromachine, 

@samitnuk have the right answer 👍 ! For any list on the MANGOPAY API you will have (by default) a 10 objects result. 

In order to solve your problem you should use pagination parameters (in URL query):
- `Page`: index of the page (start to 1) Default value: 1
- `Per_Page`: number of items returned. Default value: 10 Max: 100

For more details : https://docs.mangopay.com/guide/lists-pagination-management.

Best regards,

Audouin,
