### ISSUE TITLE
Missing UBO deactivation process

### ISSUE THREAD

**Issue by Endzel** [Mangopay/mangopay2-python-sdk#211]
According to the [MangoPay API Docs](https://docs.mangopay.com/endpoints/v2.01/ubo-declarations#e1030_update-a-ubo) referring to the updates of existing UBOs for a certain UBO Declaration, we observe that it does not exist a method in the SDK for the deletion/deactivation of existing UBOs. 

Whenever we try to update a UBO with the field present, that is not existing in the model, we receive this exception:

```
>>> query.update_query = {'user_id': 'XXX', 'ubo_declaration_id': 'XXX', 'id': 41, 'birthplace': <mangopay.utils.Birthplace object at 0x7f5dde160e90>, 'address': <mangopay.utils.Address object at 0x7f5dde160e50>, 'birthday': 790988400, 'first_name': 'Incomplete', 'last_name': 'Shareholder', 'nationality': 'ES', 'is_active': True}
>>> query.execute()
>>> AttributeError: Field named is_active not found
```

Quoting from the docs we have this, in reference for the _is_active_ field:
> To remove a UBO from your UBO declaration only put isActive to "false". You cannot activate back a UBO

This is necessary specially due to the **INCOMPLETE** status for UBO declarations, where the declaration must be updated before being able to be submitted again. Is there any other possible way to perform this action (the deactivation of a single UBO from some UBO declaration) currently through the SDK that I may have overlooked then?

Thanks in advance!

**Comment by Riwak** [comment]
Hello @Endzel  

Thanks for your report, unfortunately this is a bug  to fix, we will work on that ! 

Audouin,
