### ISSUE TITLE
The handler into the `save` base resource kwargs is always taking into account even for None value.

### ISSUE THREAD

**Issue by moumoutte** [Mangopay/mangopay2-python-sdk#237]
If I've understand correctly the save method of the base resource, it's possible to provide a specific handler a the `save` moment, otherwise the handler is taking from the initial object.

https://github.com/Mangopay/mangopay2-python-sdk/blob/master/mangopay/base.py#L190

But, in the subquery (insert or update) , only the `handler` object from the kwargs is taking into account.

https://github.com/Mangopay/mangopay2-python-sdk/blob/master/mangopay/base.py#L210
and 
https://github.com/Mangopay/mangopay2-python-sdk/blob/master/mangopay/base.py#L217

May be, it could be more resilient to use the `self._handler` attribute define at the beginning of the method ?

**Comment by mangomaxoasis** [comment]
Hey @moumoutte 
Looking into it, I'll keep you updated
Max

**Comment by mangomaxoasis** [comment]
Hi @moumoutte 
We're currently working on the handlers (https://github.com/Mangopay/mangopay2-python-sdk/issues/134)
We'll be releasing something soon
Max

**Comment by mangomaxoasis** [comment]
Added in lastest release
