### ISSUE TITLE
Embed response.headers into APIError

### ISSUE THREAD

**Issue by moumoutte** [Mangopay/mangopay2-python-sdk#238]
Hi, 

While creating the an APIError, the headers of the response are not set into the exception, so when I want to use them, I need to connect my code to signal provided by the SDK, which cause the code to be aware of two ways of error handling instead of one
APIError exception raised and connection signals emitted.

Some headers are very useful to handle correctly connection into the mangopay API like remaining call available into the server, so could you consider to add the response headers (or the response itself) into the APIError raised ?

https://github.com/Mangopay/mangopay2-python-sdk/blob/master/mangopay/api.py#L230

```python
def _create_apierror(self, result, url=None, data=None, method=None):
        # 
        # the existing code here
        #
        raise APIError(text, code=status_code, content=content, headers=result.headers)
```

**Comment by mangomaxoasis** [comment]
Hi @moumoutte 
We're on it
Max

**Comment by SoloJr** [comment]
Hi @moumoutte 

They are already set on https://github.com/Mangopay/mangopay2-python-sdk/blob/master/mangopay/api.py#L235

Mircea
