### ISSUE TITLE
Do you consider generating a swagger compatible oas3

### ISSUE THREAD

**Issue by Usui22750** [Mangopay/mangopay2-python-sdk#243]
Hello, 
On your web documentation website we can find a documentation API but there is no way of download the swagger associate to this documentation if there is one.
Have you ever consider it?
It can be pretty helpfull since there is a lot of tool to emulate a tierce API based on swagger.

Thanks in advance for your answer

**Comment by mangomaxoasis** [comment]
Hi usui22750

Yes the issue's been brought up internally, cannot confirm that it will be released in the near term

Max

**Comment by mangomaxoasis** [comment]
Cheers
