### ISSUE TITLE
Can't GET a Wallet with ID

### ISSUE THREAD

**Issue by berkkarahan** [Mangopay/mangopay2-python-sdk#244]
Hey, Berk from plentific here.

I can't get a resource using our forked mangopay python SDK. The resource I've been trying to get is a confirmed wallet resource by your customer service agents. They've asked to raise the issue here.

Our forked mangopay sdk; https://github.com/plentific/mangopay2-python-sdk

The error I am getting at our production env shell;

>>> from mangopay.resources import Wallet as MPWallet
>>> w = MPWallet.get(XXX)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/opt/venv/src/mangopaysdk/mangopay/resources.py", line 239, in get
    return super(Wallet, cls).get(*args, **kwargs)
  File "/opt/venv/src/mangopaysdk/mangopay/base.py", line 249, in get
    return cls.select().get(*args, **kwargs)
  File "/opt/venv/src/mangopaysdk/mangopay/query.py", line 61, in get
    reference))
mangopay.base.WalletDoesNotExist: instance Wallet matching reference XXX does not exist

**Comment by mangomaxoasis** [comment]
Hi Berk @berkkarahan 
We're looking into it
Max

**Comment by mangomaxoasis** [comment]
Hi @berkkarahan , 

The forked SDK is very behind our version, 
could we ask you to update to the latest version on our side?

Regards,
Max

**Comment by mangomaxoasis** [comment]
hi @berkkarahan 
Did you manage to update the version? Does the error persist

**Comment by berkkarahan** [comment]
sorry. couldn't get back to you. We seem to have solved the issue, we can close this.

**Comment by mangomaxoasis** [comment]
cool
