### ISSUE TITLE
Mangopay user updation not working.

### ISSUE THREAD

**Issue by backend-stunntech** [Mangopay/mangopay2-python-sdk#248]
I am using mango pay python adk version 3 to integrate mangopay. But when I trying to update a mangopay user I got the below error,
{APIError}{"Message":"One or several required parameters are missing or incorrect. An incorrect resource ID also raises this kind of error.","Type":"param_error","Id":"a58db418-69f7-4950-9bb0-8e6b01a98a41#1602149066","Date":1602149067.0,"errors":{"Nationality":"Object reference not set to an instance of an object.","CountryOfResidence":"Object reference not set to an instance of an object."}}

This is my code:

    nationality_iso_code = convert_to_iso_country_code(request_data['country'])
    country_of_residence_iso_code = convert_to_iso_country_code(request_data['country_of_residence'])
    dob_in_utc = convert_date_to_utc(request_data['dob'])

    natural_user = NaturalUser.get(user_profile.mango_pay_user_id)
    natural_user.first_name = request_data['first_name']
    natural_user.last_name = request_data['last_name']
    natural_user.birthday = dob_in_utc,
    natural_user.nationality = nationality_iso_code,
    natural_user.country_of_residence = country_of_residence_iso_code,
    natural_user.address.address_line_1 = request_data['address']['address_line_one']
    natural_user.address.address_line_2 = request_data['address']['address_line_two']
    natural_user.address.city = request_data['address']['city']
    natural_user.address.postal_code = request_data['address']['post_code']
    natural_user.address.country = nationality_iso_code
    natural_user.save()

I don't Know Why I got this.

**Comment by mangomaxoasis** [comment]
Looking into it 👍 
Max

**Comment by iulian03** [comment]
Hi there @backend-stunntech,

Please make sure that your `convert_to_iso_country_code ` and `country_of_residence_iso_code ` methods are returning strings.

The only way i managed to reproduce your issue was by setting those fields to objects: 
```
user.nationality = {}
user.country_of_residence = {}
```
, which is not correct.

You should have something like this:
```
user.nationality = 'FR'
user.country_of_residence = 'FR'
```

**Comment by mangomaxoasis** [comment]
Hi @backend-stunntech 
Please let me know if we need to reopen this issue
