### ISSUE TITLE
Validate user before trying to create it on API

### ISSUE THREAD

**Issue by flaviamissi** [MangoPay/mangopay2-python-sdk#25]
There are no validation for the API mandatory fields, also, the API response is not very clear on what's missing.

I can contribute on that if you agree with the change.

**Comment by hobailey** [comment]
Hi @flaviamissi, there is infact no validation in any of our SDKs, partly to keep things as simple as possible. 
As for the response giving the info that is required, the exception given always includes a part "Errors" which details each field and the error associated with this. If you feel this isn't clear enough, feel free to  make a pull request and we'll see if we can incorporate it in the next release.
Thanks!
