### ISSUE TITLE
Why `processed_date` of `UboDeclaration` resource is `IntegerField` and not `DateTimeField`?

### ISSUE THREAD

**Issue by samitnuk** [Mangopay/mangopay2-python-sdk#269]
https://github.com/Mangopay/mangopay2-python-sdk/blob/a04b8d6fc4fb259c6ee3a34391d16a41bf2a1931/mangopay/resources.py#L1454-L1456

**Comment by fredericdelordm** [comment]
Hello @samitnuk,

This has been fixed in our latest release [3.10.1](https://github.com/Mangopay/mangopay2-python-sdk/releases/tag/3.10.1).

Have a nice day,
