### ISSUE TITLE
UserLegal KYC verification

### ISSUE THREAD

**Issue by eddiebragg** [MangoPay/mangopay2-python-sdk#28]
I am using the UserLegal API to verify the KYC status.
According to the docs the ProofOfRegistration, Statute and the ShareholderDeclaration needs to be set to be verified.
The SDK doesn't seem to set these properties in the UserLegal entitiy.

**Comment by hobailey** [comment]
Hi there @eddiebragg, just to check, you know that ProofOfRegistration, Statute and the ShareholderDeclaration that are shown in the User object are just an indicator of when you've submitted these documents and that they've been accepted? 
To actually submit these docs, you need to use the KYC object process: https://docs.mangopay.com/api-references/kyc/
For info, you also need a ProofOfIdentity for both legal and natural users.
Let me know if I've misunderstood your request!

**Comment by eddiebragg** [comment]
Right ok so they are just references to the actual docs not that they have been accepted. So I will need to get all the documents to check the status. Sorry and thanks for you help.

**Comment by hobailey** [comment]
If you see them in the User object, it means they have indeed been accepted - its just the submission process is totally different :-) 
And when you actually submit a document, you can then check its Status to see how's progressing - it'll intially be CREATED, then when you're ready and you've added the pages, you can do a PUT to update the Status to VALIDATION_ASKED. Then our compliance team will remove the submission and the Status will either be updated to REFUSED or VALIDATED (so it's well worth setting up some Hooks to to be notified of the outcome, particularly in the case of a refusal).
Let me know if you have any other questions.
