### ISSUE TITLE
Getting bankaccount of user

### ISSUE THREAD

**Issue by NicolleLouis** [Mangopay/mangopay2-python-sdk#284]
Hi, I'm sorry to ask a question here but I did not find the answer in the documentation and customer support advised me to ask it here.

So, I'm creating a natural user and linking its bankaccount:
```
bank_account = BankAccount(
            owner_name=str(profile),
            user_id=profile.mangopay_account_id,
            type="IBAN",
            owner_address=address,
            iban=iban,
            bic=bic
        )
        bank_account.save()
```
This works perfectly, but I'm not able to read the bankaccount info of the user.
I tried to read it through: "user.bankaccounts.related_model" but did not find any info in this. 
Is there a way to get bankaccount info of a user?

Thanks a lot, 
Louis

**Comment by fredericdelordm** [comment]
Hello @NicolleLouis,

Thank you for contacting us.

You should have a look at this test : https://github.com/Mangopay/mangopay2-python-sdk/blob/master/tests/test_bankaccounts.py#L465.

Tell me if it's solved your issue.

Have a nice day,

**Comment by NicolleLouis** [comment]
Yes thanks a lot
