### ISSUE TITLE
Submit a KYC Document

### ISSUE THREAD

**Issue by NicolleLouis** [Mangopay/mangopay2-python-sdk#285]
Hi, I'm following the tutorial: "How to integrate a marketplace with MANGOPAY", at the step of creating KYC document and asking for their validation I have an issue.
- I'm able to create a KYC document:
`document = Document(type='IDENTITY_PROOF', user=mangopay_user)
        document.save()`
- I create a page for this document:
`page = Page(document=document, file=encoded_file, user=legal_user)
        page.save()`
However the status fo this document is CREATED:
![image](https://user-images.githubusercontent.com/30229476/121165411-889f1d00-c850-11eb-8d95-b1115465c514.png)
 I see an API endpoint to ask for validation: 
![image](https://user-images.githubusercontent.com/30229476/121165548-a3719180-c850-11eb-901c-7877852d1d24.png)

However I do not find how to ask for this validation through the sdk, the only reference I found of kyc document modification is this test: 
![image](https://user-images.githubusercontent.com/30229476/121164653-0282d680-c850-11eb-8583-762c2395f18e.png)

Should I go this way to ask for document validation? 

Thanks for the great work,
Louis

**Comment by fredericdelordm** [comment]
Hello @NicolleLouis,

Thank you for your message.
@SoloJr could you help @NicolleLouis please?

**Comment by SoloJr** [comment]
Hi @NicolleLouis 

Yes, .save() is the method you have to call.

**Comment by fredericdelordm** [comment]
Hello @NicolleLouis,

Everything is good for you?

Have a nice day,
