### ISSUE TITLE
Getting 401 Error when performing any request

### ISSUE THREAD

**Issue by axant-team** [MangoPay/mangopay2-python-sdk#29]
When performing any request we get the `Your authorization do not allow you to access to this information  - 401` error. The `ClientID` and `ClientPassword` are properly set and it works from some computers but not from others (same version of  Python `2.7.8`, requests: `2.5.3` and mangopaysdk)

See from python shell:

```
Python 2.7.8 (default, Oct 19 2014, 16:02:00) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.54)]

>>> from .lib.mangopay_singleton import SingletonMangoPay
>>> p = SingletonMangoPay()
>>> p.mangoPayApi.Config.ClientID
'testaxant'
>>> p.mangoPayApi.Config.ClientPassword
'wu...[THIS IS THE RIGHT TOKEN]'
>>> p.mangoPayApi.users.GetAll()
11:53:35,463 INFO  [requests.packages.urllib3.connectionpool] Starting new HTTPS connection (1): api.sandbox.mangopay.com
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File ".../lib/python2.7/site-packages/mangopaysdk/tools/apiusers.py", line 35, in GetAll
    usersList = self._getList('users_all', pagination)
  File ".../lib/python2.7/site-packages/mangopaysdk/tools/apibase.py", line 229, in _getList
    response = rest.Request(urlMethod, self._getRequestType(methodKey), None, pagination, additionalUrlParams)
  File ".../lib/python2.7/site-packages/mangopaysdk/tools/resttool.py", line 56, in Request
    response = self._runRequest(urlMethod, pagination, additionalUrlParams)
  File ".../lib/python2.7/site-packages/mangopaysdk/tools/resttool.py", line 104, in _runRequest
    self._checkResponseCode(response, decodedResp)
  File ".../lib/python2.7/site-packages/mangopaysdk/tools/resttool.py", line 148, in _checkResponseCode
    raise ResponseException(response.request.url, response.status_code, message)
ResponseException: Your authorization do not allow you to access to this information

**Comment by hobailey** [comment]
Hi there,
Sorry to hear you're having troubles. Unfortunately without further infos on the different environments you're testing with etc, its difficult for us to know what is wrong (if the SDKs and code are identical between all the environments) - I can see that some of your calls are fine and others are 401 as you've found. But in both cases, the request you're sending us is identical (except the authorization header). Are you sure that the Passphrase is correct in all cases? And perhaps unrelated, but make sure your temporary directory is accessible and writeable.
