### ISSUE TITLE
RecurringPayInRegistration optional billing and shipping fields

### ISSUE THREAD

**Issue by frossigneux** [Mangopay/mangopay2-python-sdk#293]
In https://www.youtube.com/watch?v=Bwe4u08CH84 at 2'33 and in https://docs.mangopay.com/endpoints/v2.01/payins#e1051_create-a-recurring-payin-registration we can see that the billing and shipping parameters are optional.
However they are mandatory in the sdk:
```
recurring_payin_registration.save()
  File "/home/user/lib/python3.8/site-packages/mangopay/base.py", line 214, in save
    raise ValueError('Missing mandatory field: ' + v.name)
ValueError: Missing mandatory field: billing
```

**Comment by fredericdelordm** [comment]
Hello @frossigneux, we are looking into it

**Comment by SoloJr** [comment]
[](https://github.com/Mangopay/mangopay2-python-sdk/pull/296)
