### ISSUE TITLE
Unable to fetch UBO Declaration by user

### ISSUE THREAD

**Issue by oziomek1** [Mangopay/mangopay2-python-sdk#301]
Hi!

[Note: I'm using package version `mangopaysdk==3.17.0`, developing in sandbox environment now]

I faced the issue when trying to fetch UBO Declaration for the specified user (LegalUser, `BUSINESS` LegalPersonType).

When I use such command:

```python
legal_user.ubodeclaration_set.all()
```

I receive:

```python
TypeError: string indices must be integers
```

Should I use some other way to fetch the reserved foreign key? In the API there's no explicit `related_name` for this foreign key?

I really need it in a case when for example admin creates a UBO declaration for a particular LegalUser in the Mangopay dashboard and I would like to sync the UBODeclaration in my system.

-----------------------

A sub-issue to the one above is submission of UBO Declaration
For a declaration in status `CREATED`

```python
ubo_declaration.status = 'VALIDATION_ASKED'
ubo_declaration.save()
```

returns
```python
{'message': 'The ressource does not exist',
 'id': '4eee825c-12bf-4cf4-b8ef-324c95bedc02#1637487515'}
```

**Comment by SoloJr** [comment]
Hi @oziomek1

I think that you will find all the answers if you look at the test examples [here](https://github.com/Mangopay/mangopay2-python-sdk/blob/master/tests/test_ubos.py).

Regards.

**Comment by oziomek1** [comment]
Thanks, I didn't realise the library can be used this way. Closing
