### ISSUE TITLE
fix for negative timestamp value fields in windows

### ISSUE THREAD

**Issue by d-nuzzo** [Mangopay/mangopay2-python-sdk#310]
Hello, 
it seems `datetime.datetime.utcfromtimestamp()` does not support dates less than 1970 in windows platform; it's used here:

https://github.com/Mangopay/mangopay2-python-sdk/blob/6ec793605a5339c042a25fd68afab7879079abae/mangopay/fields.py#L126

In code like this (if `legal_representative_birthday` of user is less than 1970):

```python
legal_user = LegalUser.get(int(id))
```
The error it returns to me is : OSError: [Errno 22] Invalid argument

I've tried this workaround, if it could be useful:

```python
            if value<0:
                value = (datetime.datetime.utcfromtimestamp(0) + datetime.timedelta(seconds=value)).date()
            else:    
                value = datetime.datetime.utcfromtimestamp(value).date()
```

have a nice day

**Comment by fredericdelordm** [comment]
Hello @d-nuzzo,

Thanks for this idea. We are going to review it and see what can be implemented in the SDK.
