### ISSUE TITLE
Create a Natural User (Payer) required fields

### ISSUE THREAD

**Issue by miles-codes** [Mangopay/mangopay2-python-sdk#313]
Hi there,
I see that you included user_category on user creation based on the latest release https://docs.mangopay.com/index.php/blog/new-release-shamrock  
Could you also set nationality and residence as not required for payers?

Thank you

**Comment by fredericdelordm** [comment]
Hello @miles-codes,

We are looking into it.

**Comment by sofaconcerts-prod** [comment]
Hi @fredericdelordm -- is there an update on this? I've just updated to 3.23 in my test environment and tried to create a Payer without nationality. It still seems to be required, based on the ValueError:

```
    raise ValueError('Missing mandatory field: ' + v.name)
ValueError: Missing mandatory field: nationality
```

**Comment by fredericdelordm** [comment]
Hello @miles-codes and @sofaconcerts-prod , it has been fixed in the latest release
