### ISSUE TITLE
GooglePayIn field error

### ISSUE THREAD

**Issue by HugoDurand** [Mangopay/mangopay2-python-sdk#331]
I've noticed that there is a field `payment_type` in the GooglePayIn class in ressource.py (L735).
Regarding to the tests and others use_cases, I think this field should rather be `payment_data`.
I tried to contribute by opening a pull request, but I wasn't able to push on the repo.

**Comment by iulian03** [comment]
Hi, @HugoDurand 
You are correct, that field is wrongly named. But since we are moving away from that old implementation, please use the new `GooglePayDirectPayIn` implementation. Thanks!
