### ISSUE TITLE
Release to pypi

### ISSUE THREAD

**Issue by Changaco** [Mangopay/mangopay2-python-sdk#35]
The current release is v1.8 but [on PyPI it's still 1.5.2](https://pypi.python.org/pypi/mangopaysdk).

**Comment by hobailey** [comment]
Hi @Changaco, thanks for the reminder, and sorry for the delay getting back to you. We've just updated the PyPi pacage too.

**Comment by Changaco** [comment]
Thanks, 10 days isn't that long a delay (especially in august), and I had a workaround so it was a minor inconvenience.
