### ISSUE TITLE
BankAccount entity IBAN and BIC in comment

### ISSUE THREAD

**Issue by Kmaschta** [Mangopay/mangopay2-python-sdk#36]
Hello,

Why IBAN and BIC attributs of BankAccount entity are in comments ?
https://github.com/Mangopay/mangopay2-python-sdk/blob/master/mangopaysdk/entities/bankaccount.py

**Comment by hobailey** [comment]
Hi @Kmaschta, this is because there are several different types of bank account - for IBAN, you need to use the BankAccountDetailsIBAN class for example.
Effectively these comments are confusing, I'll remove them :-)
