### ISSUE TITLE
Lastest version hasn't been uploaded to PyPI

### ISSUE THREAD

**Issue by Changaco** [Mangopay/mangopay2-python-sdk#38]
It's the second time I have to report this problem (https://github.com/Mangopay/mangopay2-python-sdk/issues/35), you should update your release process to include the PyPI upload.

**Comment by hobailey** [comment]
Hi @Changaco, I'm sorry for the delay, but this has just been done :-)

**Comment by Changaco** [comment]
Thanks. ;-)
