### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by applequist** [Mangopay/mangopay2-python-sdk#39]
Hi,

Is the SDK supported on python 3.5 ? 
If not is there any plan to implement a python 3.5 compatible version in a near future ? 
I'm new to python but would be happy to help in any ways...

Cheers 

Brieuc

**Comment by hobailey** [comment]
@applequist as far as I'm aware, it should indeed work with 3.5 - have you been experiencing a problem in particular?

**Comment by applequist** [comment]
None so far :+1:

**Comment by hobailey** [comment]
Great, well keep us updated :-)
