### ISSUE TITLE
doc & samples

### ISSUE THREAD

**Issue by masterofdaemon** [Mangopay/mangopay2-python-sdk#41]
Hello, all libs is old, nodejs not working, python without any doc, how i can create user etc? How i can use REST api i don't know server domain, why you don't put that info in docs? Or samples of using REST api.

**Comment by masterofdaemon** [comment]
https://www.npmjs.com/package/mangopay here is the good samples

**Comment by masterofdaemon** [comment]
but this third party lib if not working

**Comment by hobailey** [comment]
Hi @masterofdaemon, sorry you've been having troubles. This nodejs library you found is not an official one, however we're currently working on a full nodejs SDK which will be released in the next few weeks.
I appreciate the SDKs sometimes lack examples, but this is something we're working on and we'll be released a new documentation site soon to partly respond to this need.
As for the server domain, you'll find that (and a few examples) in the readme. Alternatively you could check out the unit tests for more info - for example, for creating a user that's here: https://github.com/Mangopay/mangopay2-python-sdk/blob/master/tests/testbase.py#L73
