### ISSUE TITLE
Support for client wallets

### ISSUE THREAD

**Issue by brickcap** [Mangopay/mangopay2-python-sdk#42]
Hi Everyone,

Does this library support  [client wallets api](https://docs.mangopay.com/api-references/client-wallets/)? 

If so,could you give me an example of how to use it? I couldn't figure it out from the [tests](https://github.com/Mangopay/mangopay2-python-sdk/blob/master/tests/testapiwallets.py) or by reading the [api file](https://github.com/Mangopay/mangopay2-python-sdk/blob/master/mangopaysdk/tools/apiwallets.py) 

Thanks.

**Comment by hobailey** [comment]
Hi @brickcap, these tests you mention are for normal wallets, not client wallets. But actually, the functionality you're looking for isn't yet available in the SDKs - we're working on and will update them shortly :-)

**Comment by brickcap** [comment]
Ah that answers my question! Many thanks for making this wonderful library :) I was able to use it even though I'm not all that familiar with python.  I'll keep this issue open so you can update it once the functionality is available. Feel free to close it otherwise.

**Comment by hobailey** [comment]
Sure thing :-)

**Comment by hobailey** [comment]
Hey @brickcap, just so you now, this is now included in v3 :-)
