### ISSUE TITLE
 The requested resource does not support http method 'POST'. 

### ISSUE THREAD

**Issue by Prakash-Kumar-Webkul** [Mangopay/mangopay2-python-sdk#45]
i just stated  using this library **mangopaysdk**,
 Now while creating the user `**api.clients.Create(mangopay_client_id,'test', 'test@sample.com') **`,i am getting some error like : 
**mangopaysdk.types.exceptions.responseexception.ResponseException: The requested resource does not support http method 'POST'.**

Any help will be greatly appreciated !

Here is the complete code:
 `from mangopaysdk.mangopayapi import MangoPayApi

api = MangoPayApi()
mangopay_client_id='mangopay_client_id'
mangopay_pass_phrase_code='mangopay_pass_phrase_code'
api.Config.ClientID = mangopay_client_id
api.Config.ClientPassword = mangopay_pass_phrase_code
api.Config.TempPath = "/opt/custom/payment_mangopay/"
api.Config.BaseUrl = "https://api.sandbox.mangopay.com"

client = api.clients.Create(mangopay_client_id,'test', 'test@sample.com')
print client
`

**Comment by hobailey** [comment]
Hi @Prakash-Kumar-Webkul, are you trying to create an account, or an actual user?
I imagine the latter, in which case it's something like:
```
user = UserNatural()
user.FirstName = "John"
user.LastName = "Doe"
user.Email = "john.doe@sample.org"
user.Birthday = int(time.mktime((1975, 12, 21, 0,0,0, -1, -1, -1)))
user.Nationality = "FR"
user.CountryOfResidence = "FR"
user.Occupation = "programmer"
user.IncomeRange = 3
api.users.Create(user)
```
