### ISSUE TITLE
PayInPaymentDetailsDirectCard inherits the wrong class

### ISSUE THREAD

**Issue by alexei** [Mangopay/mangopay2-python-sdk#51]
I think PayInPaymentDetailsDirectCard inherits the wrong class, see https://github.com/Mangopay/mangopay2-python-sdk/blob/master/mangopaysdk/types/payinpaymentdetailsdirectcard.py

Shouldn't it inherit from `mangopaysdk.types.payinpaymentdetails.PayInPaymentDetails` like the other payment details classes?

**Comment by hobailey** [comment]
Hey @alexei, I think you're spot on. Although I'm worried that changing that now will create breaking changes :-/

**Comment by alexei** [comment]
They inherit an empty class so aside from some type checks, I don't think the change would break anything.

Also, having a PHP background and learning from it's mistakes, I find it wrong to persist these kind of errors.
