### ISSUE TITLE
Extraneous argument in ApiUsers.UpdateUserKycDocument

### ISSUE THREAD

**Issue by alexei** [Mangopay/mangopay2-python-sdk#52]
`mangopaysdk.tools.apiusers.ApiUsers.UpdateUserKycDocument` takes a fourth, uneeded, argument in the form of `kycDocumentId`

Makye you can raise a warning in the next version and remove it completely in the following versions.

I can do it if you want.

**Comment by hobailey** [comment]
Thanks for bringing this up @alexei. Do you not think we could just remove it straight away? If someone passes a fourth arguement when it no longer is required, it wouldn't actually have any negative affect would it?

**Comment by alexei** [comment]
It would raise an error because it's a required argument so I assume current implementations (with KYC support) are using it.

So the plan would be:

1. make it optional in the next version and raise a warning if it's set
2. remove it completely in subsequent versions

You can actually create two versions and make them available (on PyPI) at the same time

I'd be happy to fork the project and open a PR for this (and the previous issue I opened)

**Comment by hobailey** [comment]
OK, thanks for the clarifications. If you'd have time for a PR, that's always much appreciated and the quickest way for us to get modifiations live :-)

**Comment by hobailey** [comment]
Thanks for the PR - I'll close this issue now.
