### ISSUE TITLE
Bundle certificates or require certifi module

### ISSUE THREAD

**Issue by alexei** [Mangopay/mangopay2-python-sdk#59]
I think the library should either ship with a certificates bundle or require the certifi Python module so that it doesn't generate warnings. I'm guessing there are users who don't know what to do with them.

**Comment by alexei** [comment]
Thoughts?

**Comment by hobailey** [comment]
Hey @alexei, I'm sorry we couldn't get to this before, but we've now released a newer and better version (v3) and I don't see that we'll be resolving this issue now since it's for a previous version :-(
