### ISSUE TITLE
PEP8 cleanup

### ISSUE THREAD

**Issue by alexei** [Mangopay/mangopay2-python-sdk#60]
The library needs some PEP8 cleanup

**Comment by alexei** [comment]
I mean mostly things like imported but not used modules

**Comment by alexei** [comment]
Thoughts?

**Comment by hobailey** [comment]
Hmm, perhaps - but you should be aware that we'll soon discontinue this SDK in favour of a totally rebuilt one (that is not based on PHP methods etc)...

**Comment by hobailey** [comment]
So although we really appreciate all these feedbacks and PRs, perhaps I could add you to the private beta of the new SDK to get your thoughts on that one instead?

**Comment by alexei** [comment]
Yeah, sure :)

We just finished implementing a library on top of this SDK and are now in the process of integrating it into our app. It might be helpful to see any upcoming changes and evaluate what it would mean to switch to the newer library.

**Comment by hobailey** [comment]
OK, no problem - just added you :-)

**Comment by hobailey** [comment]
(Feel free to create issues/PRs over there)

**Comment by hobailey** [comment]
Hey @alexei, with the release of the new v3 version, we're no longer maintaining the previous versions so I'm closing this for now I'm afraid.

**Comment by alexei** [comment]
Yeah, it's ok. We finished our client based on v2 (we were almost done when you told me about v3) and then I started to work on other features. I'll probably have some feedback for v3 when we decide to switch.

**Comment by hobailey** [comment]
Damn it, I'm sorry for that unforunate timing :-(
