### ISSUE TITLE
User.all raises exception (v3)

### ISSUE THREAD

**Issue by ma-rp** [Mangopay/mangopay2-python-sdk#69]
**When:**
User.all()

**Then:**
[Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../venv/local/lib/python2.7/site-packages/mangopay/base.py", line 157, in __repr__
    u = six.text_type(self)
TypeError: coercing to Unicode: need string or buffer, NoneType found

**Comment by gabriellupu** [comment]
@ma-rp have you tried calling `User().all()` ?

**Comment by stefanGhivi** [comment]
@ma-rp can you please provide a more elaborate context in which you used User.all() (code snippet) and also the python version you used

**Comment by ma-rp** [comment]
Hello, 
I get the error simply trying by shell. 
Here's the snippet (@gabriellupu I tried your suggestion, got the same result):

/$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mangopay
>>> mangopay.client_id = '#####'
>>> mangopay.passphrase = '##########'
>>> mangopay.api.APIRequest(sandbox=True)
<mangopay.api.APIRequest object at 0x7f5527401550>
>>> 
>>> from mangopay.resources import BankAccount, NaturalUser, User
>>> User.all()
[Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/marp/Desktop/patipami/venv/local/lib/python2.7/site-packages/mangopay/base.py", line 157, in __repr__
    u = six.text_type(self)
TypeError: coercing to Unicode: need string or buffer, NoneType found
>>> User().all()
[Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/marp/Desktop/patipami/venv/local/lib/python2.7/site-packages/mangopay/base.py", line 157, in __repr__
    u = six.text_type(self)
TypeError: coercing to Unicode: need string or buffer, NoneType found
>>>
