### ISSUE TITLE
Error when running pip install 

### ISSUE THREAD

**Issue by dev2simple** [Mangopay/mangopay2-python-sdk#72]
When running pip install, I get the following message so it is impossible to install the SDK:

IOError: [Errno 2] No such file or directory: '/tmp/pip-build-0zvymc/python-mangopay/DESCRIPTION.rst'

**Comment by hobailey** [comment]
Hey @dev2simple, thanks for letting us know. We've just released a new version (v3.0.1) with the fix, so do get back to us if that doesn't resolve the problem :-)
