### ISSUE TITLE
example in doc Document.all(user_id='an id') doesn't work

### ISSUE THREAD

**Issue by NameX44** [Mangopay/mangopay2-python-sdk#78]
Hi,

Your documentation says : 

> Once you have done with these steps, you will be able to get a list of all the uploaded documents for this particular user
> documents = Document.all(user_id=legal_user.get_pk())

But this doesn't work properly because Document's resources url doesn't contain a parameter user_id : 

`url = {
            InsertQuery.identifier: '/users/%(user_id)s/KYC/documents',
            UpdateQuery.identifier: '/users/%(user_id)s/KYC/documents',
            SelectQuery.identifier: '/KYC/documents'
        }`

[resources.py ligne 670](https://github.com/Mangopay/mangopay2-python-sdk/blob/master/mangopay/resources.py#L670)

Am I wrong ? If not how could we correct this ?

Thanks,

**Comment by NameX44** [comment]
Replace by the following works but it break all() function without parameters, because url become malformed : 

`SelectQuery.identifier: '/users/%(user_id)s/KYC/documents/'`

**Comment by gabriellupu** [comment]
Documentation has been updated, use 
```
documents = legal_user.documents.all()
```
instead of
```
documents = Document.all(user_id=legal_user.get_pk()) 
```

**Comment by mickaelpois** [comment]
close #78
