### ISSUE TITLE
Models don't allow using the API names

### ISSUE THREAD

**Issue by Changaco** [Mangopay/mangopay2-python-sdk#89]
I'm working on migrating code that uses this library, from v2 to v3, and it would be easier if data could be accessed and modified using the API names (e.g. `AuthorId`) in addition to the new python names (e.g. `author`).

If I make a Pull Request adding support for using the API names, will you merge it?

**Comment by Changaco** [comment]
To clarify, what I'm proposing is to add two methods (`__getattr__`, `__setattr__`) and one caching property (`_api_names`) to the `BaseApiModel` class.

I've done that with monkey patches in the project I'm migrating, it greatly reduces the number of necessary code changes.

Modifying the `Money` class to support title-cased attributes (`Amount` and `Currency`) is also helpful.

**Comment by mickaelpois** [comment]
@Changaco It seems to be fine and clean. Thanks for that.
