### ISSUE TITLE
Logging is inappropriate

### ISSUE THREAD

**Issue by Changaco** [Mangopay/mangopay2-python-sdk#95]
The `APIRequest` class logs all API requests and responses at the `INFO` level, and not just the URLs but the headers and bodies as well. In case of failure the information is also logged a second time at the `ERROR` level.

I think all the logging should be at the `DEBUG` level, except for a simple `ERROR` message when a request fails (containing only the URL and status code).

**Comment by mickaelpois** [comment]
Hi @Changaco, 

Thanks again for your precious feedback.
We will be looking at this ASAP, it's on our backlog in ortor to improve how this SDK could be easily used.

Stay tuned for updates about this subject !

**Comment by hobailey** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Logs issues](https://trello.com/c/nBXqLjUr/167-logs-issues)
