### ISSUE TITLE
Can't use the SDK in production environment

### ISSUE THREAD

**Issue by chocopoche** [Mangopay/mangopay2-python-sdk#96]
Some methods don't take a handler as an argument, but it's via this handler that you define the sandbox parameter. As a result, I can't NaturalUser.get(1) on a production environment. 

Here is the patch I use that fixes the issue:

```
---
 mangopay/api.py | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/mangopay/api.py b/mangopay/api.py
index 77e8198..d4d0f33 100644
--- a/mangopay/api.py
+++ b/mangopay/api.py
@@ -33,9 +33,9 @@ requests_session = requests.Session()
 
 
 class APIRequest(object):
-    def __init__(self, client_id=None, passphrase=None, api_url=None, api_sandbox_url=None, sandbox=True,
+    def __init__(self, client_id=None, passphrase=None, api_url=None, api_sandbox_url=None, sandbox=None,
                  timeout=30.0, storage_strategy=None, proxies=None):
-        if sandbox:
+        if sandbox or mangopay.sandbox:
             self.api_url = api_sandbox_url or mangopay.api_sandbox_url
         else:
             self.api_url = api_url or mangopay.api_url
-- 

```

**Comment by hobailey** [comment]
Hey @chocopoche, do you think you could do a pull request with your suggest please? It would make it a bit clearer :-) Thanks!

**Comment by Changaco** [comment]
I second this issue. The way this library manages its default handler is convoluted and broken. I had to use a monkeypatch like this:

```python
handler = mangopay.APIRequest(client_id=…, passphrase=…, sandbox=…)
mangopay.get_default_handler = mangopay.base.get_default_handler = \
    mangopay.query.get_default_handler = lambda: handler
```

**Comment by hobailey** [comment]
This has now been implemented with #97 and has just been released with v3.0.5 :-)

**Comment by lggwettmann** [comment]
Somehow, I can't connect to the production environment with this. When I call `mangopay.APIRequest(client_id=..., passphrase=..., sandbox=False)`
it still connects to the sandbox. How do you use this implementation?

**Comment by lggwettmann** [comment]
I changed 
`if sandbox or mangopay.sandbox:`
back into 
`if sandbox==True: `
and it worked for me - but that also means one has to specify Sandbox with the handler initalisation.

I'm still curious for the 'real' way how to do it. Thanks in advance for your help.

**Comment by chocopoche** [comment]
@Iggwettmann did you configured the SDK to not be in sandbox mode? I'm using:

    import mangopay
    mangopay.client_id = 'xxx'
    mangopay.passphrase = 'xxx'
    mangopay.sandbox = True

**Comment by lggwettmann** [comment]
Ah, that makes sense, of course. 

it doesn't work if you inject sandbox into the handler initialization. You might want to update that in the docs. Thanks, @chocopoche
