### ISSUE TITLE
Data is returned as bytes

### ISSUE THREAD

**Issue by Changaco** [Mangopay/mangopay2-python-sdk#99]
It seems that this library does not properly decode the data it gets from the API. I'm getting a `UnicodeDecodeError` (`'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)`) when trying to render a `FirstName` which has the value "Sébastien".

**Comment by Changaco** [comment]
The problem is <https://github.com/Mangopay/mangopay2-python-sdk/blob/9e222e632b6828bfde1aeff3b936d6f9699f5bb9/mangopay/fields.py#L83-L85>. The values are properly decoded, but then this code re-encodes them, which is a bad idea.

**Comment by gabriellupu** [comment]
Hello @Changaco !
Thanks for bringing up this issue. I did some tests locally, with the following code sequence:

```python
natural_user = NaturalUser(first_name='Sébastien',
                           last_name='Hugo',
                           address=Address(address_line_1='AddressLine1', address_line_2='AddressLine2',
                               city='City', region='Region',
                               postal_code='11222', country='FR'),
                           birthday=1300186358,
                           nationality='FR',
                           country_of_residence='FR',
                           occupation='Writer',
                           income_range='6',
                           proof_of_identity=None,
                           proof_of_address=None,
                           person_type='NATURAL',
                           email='victor@hugo.com',
                           tag='custom tag')
natural_user.save()
user = User.get(natural_user.get_pk())

import pdb; pdb.set_trace()
```
console output at breakpoint:

```
(Pdb) user.FirstName
'S\xc3\xa9bastien'

(Pdb) print user.FirstName
Sébastien
```
so the value of the FirstName is printed correctly. I have to mention that the header of the file contains `# -*- coding: utf-8 -*-`.  The test have been performed with Python 2.7.10.
Please provide me the version of Python and the script that is causing failure if possible.
Thanks!

**Comment by Changaco** [comment]
Your pdb output demonstrates exactly what I said, which is that strings are re-encoded as utf8 under python2 (you get `'S\xc3\xa9bastien'` instead of `u'S\xe9bastien'`), by the 3 lines of code I linked to in my previous comment. Solving this issue involves removing those 3 lines.

**Comment by mickaelpois** [comment]
Hello @Changaco !
I will release very soon this new fix thanks to @gabriellupu commit 👍
